spring:
  config.activate.on-profile: local-image
image:
  location:
    prefix: http://localhost:8081
    path: /Users/hyeonseung-gu/Desktop

---
spring:
  config.activate.on-profile: server-image
image:
  location:
    prefix: http://3.38.19.119:8081
    path: /home/image