server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    filter:
      order: 2
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        create_empty_composites:
          enabled: true
    open-in-view: false

# 현승구 : yml 분리 작업을 위해서 spring.config.import , profiles.active , group 활용
  config:
    import: application-database.yml
  profiles:
    include:
      - secret
      - s3
      - map
      - security
    # active 건드리지 말 것
    active: dev
    group:
      # 그룹별 묶을 설정 파일 grouping
      dev: iluvit-dev, dev-db, http
      prod: iluvit-prod, prod-db, http

  version:
    aos: 1.0.0
    ios: 1.0.0

---
spring:
  config.activate.on-profile: iluvit-dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.hibernate.SQL: info

---
spring:
  config.activate.on-profile: iluvit-prod

logging:
  level:
    org.hibernate.SQL: info

---

management:
  endpoints:
    web:
      base-path: /management

logging:
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback-spring.xml