server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        create_empty_composites:
          enabled: true
  config:
    import: application-database.yml, application-img.yml
  profiles:
    include:
      - secret
      - s3
    active: develop
    group:
      develop: iluvit-develop, h2, local-image
      release: iluvit-release, mysql, server-image

---
spring:
  config.activate.on-profile: iluvit-develop

logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config.activate.on-profile: iluvit-release

logging:
  level:
    org.hibernate.SQL: info

