server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 20MB
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        create_empty_composites:
          enabled: true
    open-in-view: false
  config:
    import: application-database.yml, application-img.yml
  profiles:
    include:
      - secret
      - s3
      - map
      - security
    active: develop
    group:
      develop: iluvit-develop, h2, local-image, http
      release: iluvit-release, mysql, server-image, ssl

---
spring:
  config.activate.on-profile: iluvit-develop
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config.activate.on-profile: iluvit-release
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate.SQL: info